packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  core-js: false
  esbuild: true
  msgpackr-extract: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@anthropic-ai/sdk@0.100.1'
